### ISSUE TITLE
Cache eviction

### ISSUE THREAD

**Issue by rtm** [ember-cli/broccoli-caching-writer#39]
Running `ember serve` I get

    broccoli-caching-writer  cache eviction due to:
    - {directory, ., 16822, 0, 0, 1428421480363}
    - {undefined} +0ms

This is on a W8.1 machine if that matters.
Any idea of what this might be or how to track it down?

**Comment by stefanpenner** [comment]
this is expected, on boot there is no cache. So there is an eviction of sorts.  I suppose we can improved the logging, and i'll do that shortly to prevent confusion.

**Comment by stefanpenner** [comment]
https://github.com/ember-cli/broccoli-caching-writer/pull/44 will fix this
