### ISSUE TITLE
add appveyor

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/broccoli-caching-writer#45]
cc @twokul got a sec good sir?

**Comment by twokul** [comment]
@stefanpenner don't have permissions :(

**Comment by stefanpenner** [comment]
I believe you can still submit a working appveyoryml and confirm on your account that it works. Also the badge

**Comment by twokul** [comment]
@stefanpenner ah

**Comment by stefanpenner** [comment]
@twokul in theory you have permission, but i suspect the appveyor <-> gh account sync is funky...
