### ISSUE TITLE
Confused docs and no cached files

### ISSUE THREAD

**Issue by BryanCrotaz** [ember-cli/broccoli-caching-writer#69]
In the readme example it uses
// options.inputFiles === array of globs, to consider for the cache key 
  
In the text below it uses
cacheInclude (default: []): An array of regular expressions...

Which one is right? Are they both right? Are they subtly different features?

**Comment by BryanCrotaz** [comment]
How do you get it to cache the entire output and refresh if any of the input files change?

I tried several attempts and ended up here, thoroughly confused. Nothing gets written to the cache folder.

```
function BroccoliSwaggerCfCompiler (inputNodes, options) {
	options = options || {};

	options.cacheInclude = [/.*/];

	this.inputNodes = Array.isArray(inputNodes) ? inputNodes : [inputNodes];

	Plugin.call(this, this.inputNodes, options);
...
```

**Comment by BryanCrotaz** [comment]
Here's a simpler one that just wraps archiver to create a zip file - really really want this one cached! :)

With the below config, nothing gets cached.

```
function BroccoliArchiver(inputNodes, options) {
  options = options || {};

	options.cacheInclude = [/.*/];
	options.inputFiles = ['**/*'];

  this.inputNodes = Array.isArray(inputNodes) ? inputNodes : [inputNodes];

	Plugin.call(this, this.inputNodes, options);

  options.archive = options.archive || "archive.zip";
  if (options.archive.indexOf('.') === -1) {
  	options.archive += '.zip';
  }

  this.options = options;
}
```

**Comment by stefanpenner** [comment]
docs looks accurate, and tests seem to confirm: https://github.com/ember-cli/broccoli-caching-writer/blob/master/tests/index.js

Please provide an isolated reproduction that demonstrates the issue and we can reopen

**Comment by BryanCrotaz** [comment]
What's the difference between `inputFiles` and `cacheInclude`?
