### ISSUE TITLE
This project appears to introduce ~221 files via itself and its deps

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/broccoli-caching-writer#75]
own files included likely by mistake:
---

- [ ] tests: 13
- [ ] appveyor.yml       1

dependencies (127):
---

 - [ ] broccoli-kitchen-sink-helpers      51
 - [ ] broccoli-plugin      17
 - [ ] rimraf      56

-- node both 2x and 3x will need to be updated.

**Comment by Turbo87** [comment]
Note that `broccoli-plugin` is currently pinned to v1.1.0, which results in duplication in my projects since most other broccoli plugins are compatible and use v1.2.1 instead.
